# Name of your workflow
name: Android Build
# Pushes code to Master branch
on:
  push:
   branches: [ "master" ]
  # Building process
jobs:
 build:
  runs-on: ubuntu-latest
  # Download Project code
  steps:
  # Installs Java 17 (No java=No project)
   - name: Check out repository 
     uses: actions/checkout@v2
     #Gradlew (No Gradle=Failed build
   - name: Set up JDK 17
     uses: actions/setup-java@v2
     with:
       distribution: 'zulu' 
       java-version: 17
   - name: Make gradlew executable
     run: chmod +x gradlew
     #Builds your app
   - name: Build with Gradle 
     run: ./gradlew assembleDebug
    

  
